{% set name = "proxystore" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proxystore-{{ version }}.tar.gz
  sha256: 11aec13496d2affbfad17f764a468d5b39fb643d37be8ae4960411e79bb86ca1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - cryptography >=39.0.1
    - cloudpickle >=1.6.0
    - globus-sdk >=3.3.0
    - lazy-object-proxy >=1.6.0
    - parsl >=1.0.0
    - python
    - redis-py >=3.4
    - click !=8.1.4

test:
  imports:
    - proxystore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gpauloski/ProxyStore
  summary: Python lazy object proxy interface for distributed stores.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
