{% set name = "proxystore" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/proxystore-{{ version }}.tar.gz
  sha256: 8d6065351d26ee28bb55a6a54c801691d9ad76a9dbbcf6d430e1ba1764bd0eb7

build:
  entry_points:
    - proxystore-endpoint = proxystore.endpoint.cli:cli
    - proxystore-globus-auth = proxystore.globus.cli:cli
    - proxystore-relay = proxystore.p2p.relay.run:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - click !=8.1.4
    - cloudpickle >=3
    - cryptography >=39.0.1
    - globus-sdk >=3.46.0,<4
    - lazy-object-proxy >=1.6.0
    - pydantic >=2,<3
    # for all python, not just py<3.11, to stay noarch: python
    - tomli
    - tomli-w
    - typing_extensions >=4.3.0

test:
  imports:
    - proxystore
  commands:
    - pip check
    - proxystore-globus-auth --help
    - proxystore-relay --help
  requires:
    - python {{ python_min }}
    - pip
    - websockets
    - tosholi
    - pydantic

about:
  home: https://github.com/gpauloski/ProxyStore
  summary: Lazy object proxy interface for distributed stores.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
    - xylar
