{% set name = "proxystore" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proxystore-{{ version }}.tar.gz
  sha256: e3bae02cf1f9a8129243c9ebcec1e7fc09f1486acf59643fd2246aec10987296

build:
  entry_points:
    - proxystore-endpoint = proxystore.endpoint.cli:cli
    - proxystore-globus-auth = proxystore.globus.cli:cli
    - proxystore-relay = proxystore.p2p.relay.run:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - click !=8.1.4
    - cloudpickle >=1.6.0
    - cryptography >=39.0.1
    - globus-sdk >=3.3.0
    - lazy-object-proxy >=1.6.0
    - typing-extensions >=4.3.0

test:
  imports:
    - proxystore
  commands:
    - pip check
    - proxystore-globus-auth --help
    - proxystore-relay --help
  requires:
    - pip

about:
  home: https://github.com/gpauloski/ProxyStore
  summary: Lazy object proxy interface for distributed stores.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
